language: node_js
node_js:
  - "6.9"
install:
  - npm install
script:
  - npm run build
after_success:
  - bash deploy.sh
env:
  global:
    secure: mAH1fUEDygz1JkpdnezSs/Bp8Dcwsf9XtBxsbGytC1xYD+GumlmaEvLCCM2s4fgRn+GCRqnyx7uz0iK7yKmlgeKHGMCOWKmr/1oU+SaXwS4Fuu2O2QxVcLC+n1/GvaVWOdqFKFl8qjtvThDbDQsIiS1hAI2UJnSNwaZLVX2bEyvNah5brx94W1qT9JVplRw4kC6+9Y+2PAkg0MYuJKl972HRCnUcapWsDOos4JApAO3/GMZA3j+xWDBQUdwN9OrLhUfPJ1JQPkJA6Xz4OvsmHuV0h4W8No16CKE+OQKT5/OJHWLWPJ+NT5asd7s1TuXva6B5aoSwjp3fUt+KZM8Ic9ZdAXQWcFp31kZxm8TgxXCUB3Q06eSutulbVR374S3HcEZBwVhSvAE52lTlEqsjOUnwh1wFTkSBMhtOfjmCFs/kfvSOn6F6AKADzNuXWzXG2ybH91xKVFHC/RtPF8XRZBQW1G8nuceyCphmqrLmvZKsTI6ikOEpnnc5Hj8lX50Hhg+9gczmene/JEZlvQQ3XE1DmqxfcoYIdshB8zuLcFgOCeZgVKOd2ZriTYDrXzOf/f9ZqBA4nFU0ZLQWpiE+ZxnTJnrXlG0kL4/vKbtj8/bdyvaYPnsAgZXq4Ovdf40It2PPNkBvamXB36o4IP7Um0l/q0vbFTJ4VNE8OgI0KkQ=
